### ISSUE TITLE
上传图片之后鼠标选中图片报错

### ISSUE THREAD

**Issue by huyawei** [uxcore/uxcore-tinymce#21]
`tinymce.min.js:10 Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.
    at A.<anonymous> (http://localhost:8000/plugins/tinymce/tinymce.min.js:10:4357)
    at t.i [as fire] (http://localhost:8000/plugins/tinymce/tinymce.min.js:8:11258)
    at A.fire (http://localhost:8000/plugins/tinymce/tinymce.min.js:8:13143)
    at p.s (http://localhost:8000/plugins/tinymce/tinymce.min.js:10:11754)
    at e (http://localhost:8000/plugins/tinymce/tinymce.min.js:2:12318)
    at HTMLHtmlElement.m (http://localhost:8000/plugins/tinymce/tinymce.min.js:2:12658)`

光标放到图片右侧按住往左侧拖拽选中倒是可以编辑图片

**Comment by huyawei** [comment]
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
